// Shared project data — imported by both the marketplace listing and detail pages
import {
  Target, Send, Mail, Megaphone, TrendingUp, Globe, BarChart3,
  Radio, FileText, Headphones, Handshake, Bot, Sparkles, Layers, Network
} from 'lucide-react';

export const PROJECT_CATEGORIES = [
  { id: 'all', label: 'All Projects', icon: Layers },
  { id: 'outbound', label: 'Outbound & Lead Gen', icon: Target },
  { id: 'outreach', label: 'Sales Outreach', icon: Send },
  { id: 'email', label: 'Email Marketing', icon: Mail },
  { id: 'brand', label: 'Brand & Social', icon: Megaphone },
  { id: 'traffic', label: 'Traffic & Growth', icon: TrendingUp },
  { id: 'intelligence', label: 'Sales Intelligence', icon: BarChart3 },
  { id: 'relationship', label: 'Relationship Mgmt', icon: Network },
  { id: 'assistant', label: 'Virtual Assistants', icon: Bot },
  { id: 'ai-matching', label: 'AI Expert Matching', icon: Sparkles },
];

export const PROJECTS = [
  {
    id: 'outbound-list-builder',
    category: 'outbound',
    number: 'Project 1.1 – 1.2',
    title: 'Dream List Builder',
    subtitle: 'Build your outbound list from 5M+ verified contacts',
    tagline: 'Get B2B contact info for every decision maker with full profiles in seconds',
    description: 'Identify and build a hyper-targeted outbound contact list drawn from 5M+ verified B2B records. Our experts define your Ideal Customer Profile (ICP), search across data sources, enrich every contact with decision-maker profiles, verified emails, phone numbers, and LinkedIn URLs — then deliver a clean, CRM-ready sheet.',
    subProjects: ['Contact Discovery (1.1)', 'Profile Enrichment & Verification (1.2)'],
    howItWorks: [
      'Define your Ideal Customer Profile (ICP) together with the expert',
      'AI scans 5M+ contact database + 3rd-party enrichment sources',
      'Expert verifies emails, phones, and LinkedIn profiles',
      'Deliver structured, CRM-ready outbound list with full decision-maker profiles',
    ],
    deliverables: [
      'Verified contact list (CSV / CRM format)',
      'Decision-maker profiles with titles & LinkedIn',
      'Company intelligence (size, revenue, tech stack)',
      'ICP score for each contact',
    ],
    expertSkills: ['Lead Generation', 'Data Research', 'Apollo.io', 'ZoomInfo', 'Clay', 'B2B Marketing'],
    targetFor: ['B2B SaaS', 'Coaches', 'Consultants', 'Professional Services', 'Marketing Agencies'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Marketing', 'Consulting', 'Professional Services'],
    difficulty: 'Beginner',
    duration: '3–7 days',
    expertCount: 14,
    completedCount: 62,
    avgRating: 4.8,
    budgetRange: '$300 – $1,200',
    icon: Target,
    gradient: 'from-blue-500 to-blue-700',
    bgLight: 'bg-blue-50',
    textColor: 'text-blue-700',
    borderColor: 'border-blue-200',
    badge: 'Most Popular',
    trending: true,
    trendingCount: 47,
    trendingLabel: '47 businesses started this week',
    successHighlight: 'Cut prospecting time by 80% — from 3 weeks to 3 days for a consulting firm',
    successROI: '80% time saved',
    expertCities: ['Mumbai', 'Bangalore', 'Delhi', 'Hyderabad', 'Pune', 'Chennai'],
    nearbyExpertCount: { Mumbai: 4, Bangalore: 6, Delhi: 3, Hyderabad: 2, Pune: 3, Chennai: 2 },
    matchScore: { 'B2B SaaS': 96, 'Technology & Software': 91, 'Marketing': 88, 'Consulting': 94, 'Professional Services': 90, 'Ecommerce': 72, 'Healthcare': 65, 'Education': 68 },
    subjects: ['ICP Strategy', 'Data Research', 'Contact Enrichment', 'Email Verification', 'LinkedIn Intelligence', 'CRM Integration'],
    tools: ['Apollo.io', 'ZoomInfo', 'Clay', 'Hunter.io', 'LinkedIn Sales Navigator', 'HubSpot'],
    faq: [
      { q: 'How accurate is the contact data?', a: 'We guarantee 90%+ email deliverability. Every contact is triple-verified through real-time email validation, phone lookup, and LinkedIn cross-reference.' },
      { q: 'How long does it take?', a: 'Most lists (up to 500 contacts) are delivered in 3–5 business days. Larger lists (1,000+) take 5–7 days depending on ICP complexity.' },
      { q: 'Can I target specific companies?', a: 'Yes — provide a target account list and the expert will find the right decision-maker contacts within those exact companies.' },
    ],
  },
  {
    id: 'sales-outreach-automation',
    category: 'outreach',
    number: 'Project 2.1 – 2.2',
    title: 'Sales Outreach Automation',
    subtitle: 'Automate your GTM processes across email, LinkedIn & phone',
    tagline: 'Automate your sales and go-to-market processes through email, LinkedIn, and phone calls',
    description: 'End-to-end outreach automation: expert sets up multi-channel sequences across cold email, LinkedIn DMs, and cold calling scripts. Includes copywriting, A/B testing, reply handling workflows, and CRM sync — so your pipeline fills on autopilot.',
    subProjects: ['Email Sequence Setup (2.1)', 'LinkedIn + Phone Automation (2.2)'],
    howItWorks: [
      'Audit your current outreach stack and CRM',
      'Build multi-channel sequence: email → LinkedIn → phone',
      'Write personalized copy for each touchpoint with A/B variants',
      'Set up automation in your tool (Outreach / Apollo / Lemlist)',
      'Launch, monitor, and optimise reply rates weekly',
    ],
    deliverables: [
      'Multi-step email sequences (3-7 touchpoints)',
      'LinkedIn connection + DM templates',
      'Cold call scripts and objection handling',
      'CRM workflow & tagging setup',
      'Weekly performance report',
    ],
    expertSkills: ['Cold Email', 'LinkedIn Outreach', 'Outreach.io', 'Apollo', 'Lemlist', 'CRM', 'Copywriting'],
    targetFor: ['B2B SaaS', 'Consultants', 'Marketing Agencies', 'Professional Services'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Marketing', 'Sales', 'Consulting'],
    difficulty: 'Intermediate',
    duration: '1–2 weeks',
    expertCount: 18,
    completedCount: 89,
    avgRating: 4.9,
    budgetRange: '$500 – $2,500',
    icon: Send,
    gradient: 'from-orange-500 to-orange-600',
    bgLight: 'bg-orange-50',
    textColor: 'text-orange-700',
    borderColor: 'border-orange-200',
    badge: 'High ROI',
    trending: true,
    trendingCount: 38,
    trendingLabel: '38 active campaigns launched this week',
    successHighlight: '$180K pipeline built in 6 weeks for a B2B SaaS startup with 3-touch sequences',
    successROI: '$180K pipeline',
    expertCities: ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad', 'Pune', 'Noida'],
    nearbyExpertCount: { Mumbai: 5, Bangalore: 8, Delhi: 4, Hyderabad: 3, Pune: 4, Chennai: 2 },
    matchScore: { 'B2B SaaS': 98, 'Technology & Software': 93, 'Marketing': 95, 'Consulting': 91, 'Professional Services': 89, 'Ecommerce': 70, 'Healthcare': 62, 'Education': 65 },
    subjects: ['Cold Email Strategy', 'LinkedIn Outreach', 'Sequence Building', 'Copywriting', 'CRM Integration', 'A/B Testing'],
    tools: ['Outreach.io', 'Apollo.io', 'Lemlist', 'Instantly.ai', 'HubSpot', 'Salesforce'],
    faq: [
      { q: 'What reply rates can I expect?', a: 'Across our campaigns, average cold email reply rates are 8–15% and LinkedIn connection acceptance is 25–40%, depending on ICP quality and message personalisation.' },
      { q: 'Do I need to have a tool already?', a: 'No. The expert will recommend the right tool for your budget and set it up from scratch. If you already have one, they will work within it.' },
      { q: 'Is this GDPR/CAN-SPAM compliant?', a: 'Yes. Every sequence is built with compliant opt-out mechanisms, and the expert follows data protection guidelines for all markets you target.' },
    ],
  },
  {
    id: 'ai-email-sales-agency',
    category: 'email',
    number: 'Email Service Agency',
    title: 'AI Email Sales Agency',
    subtitle: 'Hire AI Sales Agents to generate meetings & sales',
    tagline: 'Start with Email Outbound, Move towards Voice agents for verified meeting booking',
    description: 'A fully managed email sales agency powered by AI. Experts build, run, and optimise cold email infrastructure that books qualified meetings for your business — handling deliverability, personalisation at scale, reply management, and handoff to your sales team.',
    subProjects: ['Cold Email Infrastructure', 'AI Reply Handling', 'Voice Agent Handoff'],
    howItWorks: [
      'Set up dedicated sending domains and warm them up',
      'Build AI-personalised email campaigns at scale',
      'AI handles initial replies and qualifies leads automatically',
      'Warm leads handed off to voice agents or sales rep',
      'Track meetings booked and revenue attributed',
    ],
    deliverables: [
      'Warmed sending infrastructure (3–5 domains)',
      'Personalised email campaign at scale',
      'AI reply classification & follow-up',
      'Monthly meetings booked report',
      'Pipeline value tracking',
    ],
    expertSkills: ['Cold Email', 'Email Deliverability', 'AI Automation', 'Instantly.ai', 'Smartlead', 'Copywriting'],
    targetFor: ['Ecommerce', 'Marketing Agencies', 'B2B SaaS', 'Professional Services'],
    matchIndustries: ['Ecommerce', 'Marketing', 'B2B SaaS', 'Technology & Software', 'Professional Services'],
    difficulty: 'Advanced',
    duration: 'Ongoing (monthly retainer)',
    expertCount: 9,
    completedCount: 31,
    avgRating: 4.7,
    budgetRange: '$1,000 – $4,000 / mo',
    icon: Mail,
    gradient: 'from-green-500 to-emerald-600',
    bgLight: 'bg-green-50',
    textColor: 'text-green-700',
    borderColor: 'border-green-200',
    badge: 'Managed Service',
    trending: false,
    trendingCount: 12,
    trendingLabel: '12 agencies onboarded this month',
    successHighlight: '47 qualified meetings booked in month 1 for a marketing agency — zero manual work',
    successROI: '47 meetings / month 1',
    expertCities: ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad'],
    nearbyExpertCount: { Mumbai: 3, Bangalore: 4, Delhi: 2, Hyderabad: 2 },
    matchScore: { 'Ecommerce': 95, 'Marketing': 92, 'B2B SaaS': 88, 'Technology & Software': 82, 'Professional Services': 79, 'Consulting': 75, 'Healthcare': 58, 'Education': 55 },
    subjects: ['Email Infrastructure', 'Domain Warmup', 'AI Personalization', 'Deliverability', 'Reply Handling', 'Voice Agent Handoff'],
    tools: ['Instantly.ai', 'Smartlead', 'Mailforge', 'Clay', 'GPT-4', 'Vapi.ai'],
    faq: [
      { q: 'How many meetings can I expect?', a: 'Results vary by industry, but our managed clients average 15–50 qualified meetings per month depending on audience size and budget.' },
      { q: 'What is the minimum commitment?', a: 'We recommend at least a 3-month engagement to properly warm domains, build lists, and optimise campaigns for maximum deliverability.' },
      { q: 'How does the voice agent handoff work?', a: 'Once a reply shows buying intent, a trained voice AI agent follows up by phone within minutes to confirm the meeting and handle basic qualification.' },
    ],
  },
  {
    id: 'brand-voice-social',
    category: 'brand',
    number: 'Brand Voice Project',
    title: 'Brand Voice & Thought Leadership',
    subtitle: "Activate your brand's voice on LinkedIn, X & industry communities",
    tagline: 'Activate Thought leadership of your company on Social Media — LinkedIn, X & Industry Communities',
    description: 'Build an authoritative brand presence through consistent, high-quality thought leadership content. Experts develop your unique brand voice, create a content calendar, ghostwrite posts for LinkedIn and X, and engage with your target communities — positioning you as the go-to authority in your space.',
    subProjects: ['Brand Voice Development', 'Content Calendar & Ghostwriting', 'Community Engagement'],
    howItWorks: [
      'Brand voice discovery workshop (tone, values, audience)',
      'Competitive content audit and positioning strategy',
      'Build 30/60/90-day content calendar',
      'Expert ghostwrites and schedules posts consistently',
      'Track engagement, followers, and inbound leads generated',
    ],
    deliverables: [
      'Brand voice guide document',
      '30-day content calendar',
      '8–12 LinkedIn/X posts per month',
      'Community comment & engagement strategy',
      'Monthly analytics report',
    ],
    expertSkills: ['Content Strategy', 'Ghostwriting', 'LinkedIn Marketing', 'Twitter/X', 'Brand Strategy', 'Copywriting'],
    targetFor: ['Coaches', 'Consultants', 'Course Creators', 'Professional Services', 'Ecommerce'],
    matchIndustries: ['Coaching', 'Consulting', 'Education', 'Ecommerce', 'Professional Services', 'Marketing'],
    difficulty: 'Intermediate',
    duration: 'Ongoing (monthly)',
    expertCount: 22,
    completedCount: 104,
    avgRating: 4.9,
    budgetRange: '$800 – $3,000 / mo',
    icon: Megaphone,
    gradient: 'from-violet-500 to-purple-600',
    bgLight: 'bg-violet-50',
    textColor: 'text-violet-700',
    borderColor: 'border-violet-200',
    badge: 'Top Rated',
    trending: true,
    trendingCount: 52,
    trendingLabel: '52 coaches & consultants joined this week',
    successHighlight: '3.2x inbound lead increase in 60 days — from 0 to 12 inbound/month for a SaaS founder',
    successROI: '3.2x inbound leads',
    expertCities: ['Mumbai', 'Bangalore', 'Delhi', 'Pune', 'Hyderabad', 'Chennai', 'Kolkata'],
    nearbyExpertCount: { Mumbai: 7, Bangalore: 9, Delhi: 5, Hyderabad: 4, Pune: 5, Chennai: 3, Kolkata: 2 },
    matchScore: { 'Coaching': 98, 'Consulting': 97, 'Education': 94, 'Ecommerce': 90, 'Professional Services': 92, 'Marketing': 95, 'B2B SaaS': 85, 'Technology & Software': 80 },
    subjects: ['Brand Voice Development', 'Content Strategy', 'LinkedIn Marketing', 'Twitter/X Growth', 'Community Engagement', 'Thought Leadership'],
    tools: ['LinkedIn', 'Twitter/X', 'Taplio', 'Buffer', 'Canva', 'Notion'],
    faq: [
      { q: 'Do you write the posts or do I?', a: 'Your expert ghostwrites everything based on your voice guide — you review and approve before anything goes live. Most clients approve 90%+ without edits after month 1.' },
      { q: 'How long before I see results?', a: 'Engagement growth typically starts in weeks 3–4. Inbound leads from content usually appear in months 2–3 as authority builds.' },
      { q: 'Can you manage multiple platforms?', a: 'Yes. We can simultaneously manage LinkedIn, X (Twitter), and industry-specific communities like Slack groups or Reddit under one retainer.' },
    ],
  },
  {
    id: 'traffic-abm',
    category: 'traffic',
    number: 'Gatekeeping Project',
    title: 'Traffic × ABM Agency',
    subtitle: 'Drive hyper-targeted traffic with Account-Based Marketing',
    tagline: 'Combine paid traffic with ABM to reach decision makers at your dream accounts',
    description: 'Account-Based Marketing meets performance advertising. Experts build and run ABM campaigns targeting specific companies and personas across LinkedIn Ads, Google Ads, and programmatic channels — ensuring every dollar reaches actual decision makers at your target accounts.',
    subProjects: ['Target Account List Build', 'ABM Campaign Setup', 'Paid Traffic Management'],
    howItWorks: [
      'Build Target Account List (TAL) from ideal customer profile',
      'Set up LinkedIn Matched Audiences and Google Customer Match',
      'Create personalised ad creatives for each account segment',
      'Run retargeting sequences to warm up accounts over time',
      'Track account engagement and pipeline influence',
    ],
    deliverables: [
      'Target Account List (TAL)',
      'ABM campaign strategy document',
      'Ad creatives for each account segment',
      'Weekly performance dashboard',
      'Account engagement report',
    ],
    expertSkills: ['ABM', 'LinkedIn Ads', 'Google Ads', 'Paid Advertising', 'Demandbase', 'Terminus', '6sense'],
    targetFor: ['B2B SaaS', 'Marketing Agencies', 'Enterprise Software'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Marketing', 'Enterprise Software'],
    difficulty: 'Advanced',
    duration: '2–4 weeks setup + ongoing',
    expertCount: 11,
    completedCount: 28,
    avgRating: 4.6,
    budgetRange: '$1,500 – $5,000 / mo',
    icon: TrendingUp,
    gradient: 'from-cyan-500 to-teal-600',
    bgLight: 'bg-cyan-50',
    textColor: 'text-cyan-700',
    borderColor: 'border-cyan-200',
    badge: 'Enterprise',
    trending: false,
    trendingCount: 9,
    trendingLabel: '9 enterprise campaigns live',
    successHighlight: '4.1x ROAS on LinkedIn ABM targeting CFOs at 50-company account list for a fintech SaaS',
    successROI: '4.1x ROAS',
    expertCities: ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad'],
    nearbyExpertCount: { Mumbai: 3, Bangalore: 5, Delhi: 2, Hyderabad: 2, Pune: 1 },
    matchScore: { 'B2B SaaS': 95, 'Technology & Software': 92, 'Marketing': 88, 'Enterprise Software': 97, 'Fintech': 90, 'Healthcare': 60, 'Ecommerce': 65, 'Education': 58 },
    subjects: ['ABM Strategy', 'Target Account Selection', 'LinkedIn Ads', 'Google Ads', 'Retargeting', 'Account Engagement Tracking'],
    tools: ['LinkedIn Campaign Manager', 'Google Ads', 'Demandbase', '6sense', 'Terminus', 'HubSpot'],
    faq: [
      { q: 'What budget do I need for ads?', a: 'We recommend a minimum ad spend of $2,000/month for LinkedIn and $1,500/month for Google to generate statistically meaningful data. The agency fee is separate.' },
      { q: 'How many target accounts should I start with?', a: 'Starting with 50–200 target accounts gives you enough data to optimise while keeping creative production manageable. We can scale to 500+ accounts once the program matures.' },
      { q: 'How long before pipeline is influenced?', a: 'ABM is a long game — expect meaningful pipeline influence signals at the 6–8 week mark, with first attributable opportunities typically in month 3.' },
    ],
  },
  {
    id: 'inbound-traffic',
    category: 'traffic',
    number: 'Hunting Project',
    title: 'Inbound Aggregation',
    subtitle: 'Website traffic & inbound lead aggregation system',
    tagline: 'Capture, qualify, and route inbound traffic from every channel into your pipeline',
    description: 'Build a complete inbound engine: SEO content, conversion rate optimisation, lead magnet creation, and automated lead routing. Experts ensure every visitor who lands on your site has the highest chance of converting — and that converted leads are instantly routed to the right team.',
    subProjects: ['SEO & Content Funnel', 'CRO & Lead Capture', 'Lead Routing Automation'],
    howItWorks: [
      'Audit current website traffic and conversion points',
      'Build keyword strategy and SEO content plan',
      'Create lead magnets (ebooks, tools, templates)',
      'Set up lead capture forms, chatbots, and landing pages',
      'Build automated lead scoring and routing rules',
    ],
    deliverables: [
      'SEO content calendar (3-month)',
      'Optimised landing pages',
      '2–3 lead magnets',
      'Lead capture & routing automation',
      'Monthly traffic & conversion report',
    ],
    expertSkills: ['SEO', 'CRO', 'Content Marketing', 'HubSpot', 'Webflow', 'Google Analytics', 'Lead Generation'],
    targetFor: ['Ecommerce', 'Coaches', 'Course Creators', 'B2B SaaS'],
    matchIndustries: ['Ecommerce', 'Coaching', 'Education', 'B2B SaaS', 'Technology & Software'],
    difficulty: 'Intermediate',
    duration: '3–4 weeks',
    expertCount: 16,
    completedCount: 57,
    avgRating: 4.7,
    budgetRange: '$700 – $2,800',
    icon: Globe,
    gradient: 'from-teal-500 to-cyan-600',
    bgLight: 'bg-teal-50',
    textColor: 'text-teal-700',
    borderColor: 'border-teal-200',
    badge: null,
    trending: true,
    trendingCount: 24,
    trendingLabel: '24 new funnels launched this week',
    successHighlight: '210% organic traffic growth in 90 days for a course creator using SEO + lead magnet combo',
    successROI: '210% traffic growth',
    expertCities: ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad', 'Pune', 'Chennai'],
    nearbyExpertCount: { Mumbai: 4, Bangalore: 7, Delhi: 3, Hyderabad: 3, Pune: 3, Chennai: 2 },
    matchScore: { 'Ecommerce': 96, 'Coaching': 93, 'Education': 95, 'B2B SaaS': 87, 'Technology & Software': 82, 'Marketing': 89, 'Professional Services': 78, 'Consulting': 75 },
    subjects: ['SEO Strategy', 'Content Marketing', 'Conversion Rate Optimisation', 'Lead Magnet Creation', 'Landing Page Design', 'Lead Routing Automation'],
    tools: ['Ahrefs', 'SEMrush', 'Webflow', 'HubSpot', 'Google Analytics', 'Hotjar'],
    faq: [
      { q: 'Do you write the SEO content or just the strategy?', a: 'Both — your expert builds the keyword strategy AND writes the content or manages content writers. You decide the level of involvement.' },
      { q: 'How fast can I rank on Google?', a: 'New content typically starts gaining traction in 6–12 weeks. Competitive keywords take longer; long-tail keywords can rank within 30 days.' },
      { q: 'What lead magnets work best?', a: 'ROI calculators, industry benchmarks, templates, and free tools convert best. Your expert will recommend the right format based on your audience and offer.' },
    ],
  },
  {
    id: 'intent-social-listening',
    category: 'intelligence',
    number: 'Observation Project',
    title: 'Intent × Social Listening',
    subtitle: 'Listen for buying intent across LinkedIn, Reddit, G2 & Gartner',
    tagline: 'Detect intent signals across social media and review platforms in real time',
    description: 'Monitor buying signals across LinkedIn, Reddit, G2, Gartner Peer Insights, and custom communities. Experts set up automated listening streams that surface prospects actively researching solutions like yours — and build workflows to engage them at exactly the right moment.',
    subProjects: ['Intent Signal Setup', 'Social Listening Streams', 'Engagement Workflow'],
    howItWorks: [
      'Map the platforms where your buyers research and hang out',
      'Set up keyword and intent monitoring across each platform',
      'Build scoring model for signal strength and purchase proximity',
      'Create engagement playbooks for each signal type',
      'Deliver weekly intent report with prioritised action items',
    ],
    deliverables: [
      'Intent monitoring dashboard',
      'Weekly buyer signal report',
      'Engagement playbooks per signal type',
      'Automated Slack/CRM alerts',
      'Competitive intelligence summary',
    ],
    expertSkills: ['Social Listening', 'Intent Data', 'Bombora', 'G2', 'LinkedIn', 'Sales Intelligence', 'Automation'],
    targetFor: ['B2B SaaS', 'Marketing Agencies', 'Consultants'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Marketing', 'Consulting'],
    difficulty: 'Advanced',
    duration: 'Ongoing (monthly)',
    expertCount: 8,
    completedCount: 19,
    avgRating: 4.8,
    budgetRange: '$600 – $2,000 / mo',
    icon: Radio,
    gradient: 'from-blue-600 to-blue-800',
    bgLight: 'bg-blue-50',
    textColor: 'text-blue-800',
    borderColor: 'border-blue-200',
    badge: 'Advanced',
    trending: false,
    trendingCount: 8,
    trendingLabel: '8 listening streams active',
    successHighlight: '31 warm inbound conversations started in week 1 from Reddit + LinkedIn intent signals',
    successROI: '31 warm convos / week 1',
    expertCities: ['Bangalore', 'Mumbai', 'Delhi'],
    nearbyExpertCount: { Mumbai: 2, Bangalore: 4, Delhi: 2 },
    matchScore: { 'B2B SaaS': 97, 'Technology & Software': 93, 'Marketing': 91, 'Consulting': 88, 'Professional Services': 80, 'Ecommerce': 65, 'Healthcare': 58, 'Education': 55 },
    subjects: ['Intent Signal Monitoring', 'Social Listening', 'Competitor Intelligence', 'Signal Scoring', 'Reddit & G2 Monitoring', 'Engagement Playbooks'],
    tools: ['Bombora', 'G2 Buyer Intent', 'LinkedIn Sales Nav', 'Reddit API', 'Gartner Peer Insights', 'Slack'],
    faq: [
      { q: 'What does an "intent signal" actually look like?', a: 'Examples: someone posts on Reddit asking "best [your category] tools?", a competitor gets a 1-star G2 review, a target account is browsing your category on G2, or a LinkedIn user asks for vendor recommendations.' },
      { q: 'How do I act on the signals once I get them?', a: 'Your expert builds engagement playbooks — specific response templates for each signal type. You review and send, or the expert engages on your behalf.' },
      { q: 'Will this work for my niche industry?', a: 'Yes. We customise listening keywords, subreddits, G2 categories, and LinkedIn groups specifically to your ICP. Niche markets often have stronger intent signal quality.' },
    ],
  },
  {
    id: 'connector-relationship',
    category: 'relationship',
    number: 'Connector Project',
    title: 'Connection & Relationship Manager',
    subtitle: 'Manage inbound & outbound LinkedIn connections on your behalf',
    tagline: 'Accept, respond & warm up connections — on your behalf',
    description: 'A fully managed LinkedIn relationship service. Experts monitor your LinkedIn inbox, accept relevant connection requests, send personalised intro messages, and warm up cold connections through consistent engagement — growing your network with the right people while you focus on closing.',
    subProjects: ['Connection Request Management', 'Warm-up Sequences', 'Inbox Management'],
    howItWorks: [
      'Audit your LinkedIn network and define connection criteria',
      'Expert monitors and responds to connection requests daily',
      'Build warm-up message sequences for new connections',
      "Engage with target accounts' posts to stay visible",
      'Weekly report on new connections and conversations started',
    ],
    deliverables: [
      '50–200 new qualified connections/month',
      'Personalised outreach templates',
      'LinkedIn inbox management',
      'Warm-up engagement schedule',
      'Weekly connection & conversation report',
    ],
    expertSkills: ['LinkedIn', 'Social Selling', 'Copywriting', 'CRM', 'Relationship Building'],
    targetFor: ['Coaches', 'Consultants', 'Professional Services', 'B2B SaaS'],
    matchIndustries: ['Coaching', 'Consulting', 'Professional Services', 'B2B SaaS', 'Technology & Software'],
    difficulty: 'Beginner',
    duration: 'Ongoing (monthly)',
    expertCount: 20,
    completedCount: 78,
    avgRating: 4.8,
    budgetRange: '$400 – $1,200 / mo',
    icon: Handshake,
    gradient: 'from-pink-500 to-rose-600',
    bgLight: 'bg-pink-50',
    textColor: 'text-pink-700',
    borderColor: 'border-pink-200',
    badge: null,
    trending: false,
    trendingCount: 19,
    trendingLabel: '19 consultants enrolled this month',
    successHighlight: '180 new targeted LinkedIn connections in 30 days — 14 converted to discovery calls',
    successROI: '14 discovery calls / month',
    expertCities: ['Mumbai', 'Bangalore', 'Delhi', 'Pune', 'Hyderabad', 'Chennai', 'Kolkata'],
    nearbyExpertCount: { Mumbai: 6, Bangalore: 8, Delhi: 4, Hyderabad: 3, Pune: 4, Chennai: 3, Kolkata: 2 },
    matchScore: { 'Coaching': 96, 'Consulting': 95, 'Professional Services': 94, 'B2B SaaS': 89, 'Technology & Software': 83, 'Marketing': 85, 'Ecommerce': 72, 'Education': 78 },
    subjects: ['LinkedIn Strategy', 'Connection Management', 'Warm-up Sequences', 'Inbox Management', 'Social Selling', 'Relationship Tracking'],
    tools: ['LinkedIn Sales Navigator', 'Dripify', 'HubSpot CRM', 'Notion', 'PhantomBuster', 'Slack'],
    faq: [
      { q: 'Is this safe for my LinkedIn account?', a: 'Yes. We operate within LinkedIn\'s limits and use human-in-the-loop workflows, not bots. Your expert handles everything manually or via approved tools at compliant volumes.' },
      { q: 'Do I give you access to my account?', a: 'You share a managed login with your expert via a secure password manager. Activity is fully transparent — you receive a weekly log of everything done.' },
      { q: 'What types of connections will you target?', a: 'You define the ICP (job title, company size, industry, location) during onboarding. The expert then targets only connections matching your criteria.' },
    ],
  },
  {
    id: 'demo-prep-crm',
    category: 'intelligence',
    number: 'Preparation Project',
    title: 'Demo Prep & CRM Research Brief',
    subtitle: 'For each scheduled demo, get a CRM-ready research brief',
    tagline: 'Know everything about your prospect before the call — automatically',
    description: 'Before every demo or sales call, get a structured research brief: company profile, recent news, identified pain points, tech stack, decision makers, LinkedIn activity, and talking points — delivered to your CRM as a note, so your reps walk in fully prepared.',
    subProjects: ['Company Research Automation', 'Pain Point Identification', 'CRM Note Delivery'],
    howItWorks: [
      'Trigger fires when demo is booked in your calendar or CRM',
      'Expert or AI researches the company and key stakeholders',
      'Pain points identified from job listings, reviews, and news',
      'Research brief formatted and pushed to CRM deal record',
      'Sales rep receives Slack alert with brief 30 mins before call',
    ],
    deliverables: [
      'Structured company profile per prospect',
      'Key stakeholder LinkedIn profiles',
      'Pain points and talking points',
      'Recent news and intent triggers',
      'CRM note + Slack notification',
    ],
    expertSkills: ['Sales Research', 'CRM', 'HubSpot', 'Salesforce', 'Sales Intelligence', 'Automation'],
    targetFor: ['B2B SaaS', 'Professional Services', 'Marketing Agencies'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Professional Services', 'Marketing', 'Consulting'],
    difficulty: 'Intermediate',
    duration: 'Per demo or ongoing',
    expertCount: 12,
    completedCount: 43,
    avgRating: 4.9,
    budgetRange: '$50–$150 per brief or $500/mo',
    icon: FileText,
    gradient: 'from-amber-500 to-orange-500',
    bgLight: 'bg-amber-50',
    textColor: 'text-amber-700',
    borderColor: 'border-amber-200',
    badge: 'New',
    trending: false,
    trendingCount: 15,
    trendingLabel: '15 teams using automated prep',
    successHighlight: 'Sales team win rate jumped from 22% to 38% in Q1 after implementing pre-call research briefs',
    successROI: '+16% win rate',
    expertCities: ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad', 'Pune'],
    nearbyExpertCount: { Mumbai: 3, Bangalore: 5, Delhi: 2, Hyderabad: 2, Pune: 2 },
    matchScore: { 'B2B SaaS': 94, 'Technology & Software': 90, 'Professional Services': 92, 'Marketing': 85, 'Consulting': 89, 'Ecommerce': 65, 'Healthcare': 70, 'Education': 62 },
    subjects: ['Company Research', 'Stakeholder Profiling', 'Pain Point Analysis', 'Tech Stack Identification', 'CRM Automation', 'Pre-call Intelligence'],
    tools: ['HubSpot', 'Salesforce', 'Clay', 'Firecrawl', 'LinkedIn Sales Nav', 'Calendly'],
    faq: [
      { q: 'How long does one research brief take?', a: 'Standard briefs (company overview + 2 stakeholders) take 30–60 minutes per prospect. Deep-dive briefs with competitive analysis take 90–120 minutes.' },
      { q: 'Can this work with any CRM?', a: 'Yes. We support HubSpot, Salesforce, Pipedrive, and most other CRMs via Zapier/Make. A custom integration can be built for enterprise setups.' },
      { q: 'What if my sales team has 10 demos a week?', a: 'We scale with you. Our team-based plans handle 20, 50, or 100+ briefs per month. Volume pricing applies above 20 briefs/month.' },
    ],
  },
  {
    id: 'call-intelligence-crm',
    category: 'intelligence',
    number: 'Listening Project',
    title: 'Call Intelligence × CRM',
    subtitle: 'Post-call intelligence: AI transcription, insights & CRM updates',
    tagline: 'Every sales call becomes structured data, coaching insights, and pipeline actions',
    description: 'Transform your post-call workflow. Experts set up AI call recording and transcription, extract deal intelligence (objections, next steps, competitor mentions), auto-update your CRM, and surface coaching insights for your team — turning every call into a data asset.',
    subProjects: ['Call Recording & Transcription', 'CRM Auto-Update', 'Coaching & Analytics'],
    howItWorks: [
      'Connect call recording tool (Gong / Chorus / Fireflies)',
      'AI transcribes and tags every call automatically',
      'Key insights extracted: objections, next steps, competitors',
      'CRM deal record updated with call summary and tasks',
      'Manager receives weekly coaching report by rep',
    ],
    deliverables: [
      'Call recording + transcription setup',
      'AI insight extraction workflow',
      'Automated CRM update rules',
      'Weekly coaching report template',
      'Deal risk scoring from call signals',
    ],
    expertSkills: ['Gong', 'Chorus', 'Fireflies', 'CRM', 'Salesforce', 'HubSpot', 'Revenue Intelligence'],
    targetFor: ['B2B SaaS', 'Marketing Agencies', 'Professional Services'],
    matchIndustries: ['B2B SaaS', 'Technology & Software', 'Professional Services', 'Marketing'],
    difficulty: 'Advanced',
    duration: '1 week setup + ongoing',
    expertCount: 7,
    completedCount: 22,
    avgRating: 4.7,
    budgetRange: '$800 – $2,500',
    icon: Headphones,
    gradient: 'from-slate-500 to-slate-700',
    bgLight: 'bg-slate-50',
    textColor: 'text-slate-700',
    borderColor: 'border-slate-200',
    badge: null,
    trending: false,
    trendingCount: 7,
    trendingLabel: '7 sales teams onboarded',
    successHighlight: 'Deal slippage reduced by 35% after call intelligence surfaced at-risk signals automatically',
    successROI: '35% less deal slippage',
    expertCities: ['Bangalore', 'Mumbai', 'Delhi'],
    nearbyExpertCount: { Mumbai: 2, Bangalore: 3, Delhi: 2 },
    matchScore: { 'B2B SaaS': 92, 'Technology & Software': 88, 'Professional Services': 87, 'Marketing': 83, 'Consulting': 80, 'Ecommerce': 60, 'Healthcare': 65, 'Education': 58 },
    subjects: ['Call Recording Setup', 'AI Transcription', 'Deal Intelligence Extraction', 'CRM Auto-Update', 'Coaching Analytics', 'Pipeline Risk Scoring'],
    tools: ['Gong', 'Chorus', 'Fireflies.ai', 'HubSpot', 'Salesforce', 'Slack'],
    faq: [
      { q: 'Do I need Gong specifically?', a: 'No. We work with Gong, Chorus, Fireflies, Otter.ai, or any recording tool you already use. We can also set up a new tool from scratch.' },
      { q: 'Can it identify competitor mentions automatically?', a: 'Yes. The system flags any mention of competitor names with timestamps, so your team knows which deals have active competitive pressure.' },
      { q: 'Is call recording legal?', a: 'Laws vary by region. Your expert will configure appropriate consent flows and recording disclosures for your jurisdictions before going live.' },
    ],
  },
  {
    id: 'virtual-assistant-marketing',
    category: 'assistant',
    number: 'Project 4',
    title: 'Marketing Virtual Assistant',
    subtitle: 'Pre-trained AI-powered virtual assistants for business growth',
    tagline: 'Handle social media, emails, inbox, tech and more — trained to build your business online',
    description: 'A Karya-trained virtual assistant equipped with a personalised DoingBlueprint — a structured plan defining exactly what needs to be done, in what order, and what "done" looks like. Unlike generic hires who wait for instructions, our Marketing VAs work proactively from day one.',
    subProjects: ['Social Media VA', 'Email & Inbox VA', 'Tech & Automation VA'],
    howItWorks: [
      'Discovery call: map your recurring tasks and priorities',
      'Build your DoingBlueprint (tasks, order, definition of done)',
      'Match you with a pre-trained VA from our vetted roster',
      'VA starts executing from blueprint on Day 1',
      'Weekly check-in and blueprint refinement',
    ],
    deliverables: [
      'Personalised DoingBlueprint document',
      'Dedicated VA with relevant tool training',
      'Weekly task completion report',
      'SOP library built over time',
      'Escalation process for edge cases',
    ],
    expertSkills: ['Social Media', 'Email Management', 'Content Scheduling', 'Canva', 'Notion', 'Zapier', 'Admin'],
    targetFor: ['Coaches', 'Course Creators', 'Consultants', 'Ecommerce', 'Professional Services'],
    matchIndustries: ['Coaching', 'Education', 'Ecommerce', 'Consulting', 'Professional Services'],
    difficulty: 'Beginner',
    duration: 'Ongoing (full-time or part-time)',
    expertCount: 35,
    completedCount: 142,
    avgRating: 4.8,
    budgetRange: '$600 – $2,500 / mo',
    icon: Bot,
    gradient: 'from-emerald-500 to-green-600',
    bgLight: 'bg-emerald-50',
    textColor: 'text-emerald-700',
    borderColor: 'border-emerald-200',
    badge: 'Most Hired',
    trending: true,
    trendingCount: 71,
    trendingLabel: '71 VAs matched this week',
    successHighlight: '22 hours/week saved for a course creator — content, emails, and community managed end-to-end',
    successROI: '22 hrs/week saved',
    expertCities: ['Mumbai', 'Bangalore', 'Delhi', 'Hyderabad', 'Pune', 'Chennai', 'Kolkata', 'Ahmedabad', 'Jaipur'],
    nearbyExpertCount: { Mumbai: 10, Bangalore: 12, Delhi: 8, Hyderabad: 6, Pune: 7, Chennai: 5, Kolkata: 4, Ahmedabad: 3, Jaipur: 2 },
    matchScore: { 'Coaching': 97, 'Education': 96, 'Ecommerce': 94, 'Consulting': 92, 'Professional Services': 93, 'Marketing': 89, 'B2B SaaS': 82, 'Technology & Software': 78 },
    subjects: ['DoingBlueprint Creation', 'Social Media Management', 'Email & Inbox Management', 'Content Scheduling', 'Admin & Operations', 'Tech & Automation'],
    tools: ['Notion', 'Canva', 'Buffer', 'Zapier', 'Google Workspace', 'Slack'],
    faq: [
      { q: 'What is a DoingBlueprint?', a: 'A DoingBlueprint is a structured document we create with you that defines every recurring task, the order to do them, the tools to use, and what "done" looks like. Your VA follows this from day one.' },
      { q: 'Is the VA full-time or part-time?', a: 'Both options available — 20hrs/week (part-time) from $600/mo or 40hrs/week (full-time) from $1,200/mo. Hours are tracked transparently.' },
      { q: 'What if the VA isn\'t a good fit?', a: 'We offer a free replacement within the first 14 days if the match isn\'t right. After that, replacements are handled within 48 hours with no extra cost.' },
    ],
  },
  {
    id: 'ai-expert-matching',
    category: 'ai-matching',
    number: 'Project 5.XX',
    title: 'AI Expert Finder & Negotiator',
    subtitle: "The AI agent that finds, vets & negotiates with India's top 5% experts",
    tagline: 'Find, vet, and negotiate with AI-powered fractional experts and agencies at scale',
    description: "Stop spending weeks sourcing freelancers. Our AI agent searches Karya's network of top 5% AI-powered fractional experts and agencies, automatically vets them against your requirements, and handles initial negotiation — presenting you with 3 vetted candidates ready to start.",
    subProjects: ['AI-Powered Talent Search', 'Automated Vetting', 'Negotiation & Onboarding'],
    howItWorks: [
      'Submit your project brief (role, skills, budget, timeline)',
      'AI searches and scores 500+ expert profiles',
      'Top 10 candidates auto-vetted against your criteria',
      'AI handles initial outreach and negotiation',
      'You receive 3 final candidates with proposals',
    ],
    deliverables: [
      '3 vetted expert proposals',
      'Skill match scores and work samples',
      'Negotiated rate within your budget',
      'Onboarding checklist for chosen expert',
      'Replacement guarantee (30 days)',
    ],
    expertSkills: ['Talent Sourcing', 'Technical Assessment', 'Negotiation', 'Project Management', 'AI Tools'],
    targetFor: ['B2B SaaS', 'Marketing Agencies', 'Ecommerce', 'Professional Services', 'Coaches'],
    matchIndustries: ['B2B SaaS', 'Marketing', 'Ecommerce', 'Technology & Software', 'Professional Services', 'Coaching', 'Consulting'],
    difficulty: 'Beginner',
    duration: '48–72 hours',
    expertCount: 5,
    completedCount: 67,
    avgRating: 4.9,
    budgetRange: 'Free (platform fee on hire)',
    icon: Sparkles,
    gradient: 'from-violet-600 to-blue-600',
    bgLight: 'bg-violet-50',
    textColor: 'text-violet-700',
    borderColor: 'border-violet-200',
    badge: 'AI-Powered',
    trending: true,
    trendingCount: 29,
    trendingLabel: '29 matches made this week',
    successHighlight: 'Full-stack growth team of 4 assembled in 72 hours — agency avoided 6 weeks of sourcing',
    successROI: '6 weeks saved on hiring',
    expertCities: ['Mumbai', 'Bangalore', 'Delhi', 'Hyderabad', 'Pune', 'Chennai', 'Kolkata', 'Ahmedabad'],
    nearbyExpertCount: { Mumbai: 2, Bangalore: 2, Delhi: 1, Hyderabad: 1, Pune: 1 },
    matchScore: { 'B2B SaaS': 90, 'Marketing': 92, 'Ecommerce': 88, 'Technology & Software': 85, 'Professional Services': 88, 'Coaching': 90, 'Consulting': 91, 'Education': 82 },
    subjects: ['Requirements Analysis', 'AI Talent Search', 'Automated Vetting', 'Skill Matching', 'Rate Negotiation', 'Expert Onboarding'],
    tools: ['Karya-AI Platform', 'LinkedIn', 'GitHub', 'Portfolio Review', 'Video Interview', 'Contract Management'],
    faq: [
      { q: 'How is this different from just browsing the Expert Marketplace?', a: 'The AI Finder is fully managed — you submit a brief and receive 3 pre-vetted candidates with negotiated rates within 72 hours. No browsing, no back-and-forth.' },
      { q: 'What is the platform fee?', a: 'The search is free. When you hire, a one-time 10% fee applies to the first month\'s invoice. Ongoing payments go directly between you and the expert.' },
      { q: 'What is the replacement guarantee?', a: 'If your hired expert doesn\'t deliver within the first 30 days, we source a replacement at zero cost and cover up to $500 of transition costs.' },
    ],
  },
];
